// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBsiQ48HB6vdAnIPkOhxhTi4WxuUyn0oho',
    appId: '1:237824966932:web:5e53583db15500554a8201',
    messagingSenderId: '237824966932',
    projectId: 'darwinz-login',
    authDomain: 'darwinz-login.firebaseapp.com',
    storageBucket: 'darwinz-login.appspot.com',
    measurementId: 'G-NYQH133B3N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtfm3MGD7Nzk1OU76BYdBpI1NKQTY2ZUQ',
    appId: '1:237824966932:android:8e70f3161dcaa7e94a8201',
    messagingSenderId: '237824966932',
    projectId: 'darwinz-login',
    storageBucket: 'darwinz-login.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCg92mpGU9KTuDOsmLkyaVlC51ZNL4EFsU',
    appId: '1:237824966932:ios:cd626b074776aa6b4a8201',
    messagingSenderId: '237824966932',
    projectId: 'darwinz-login',
    storageBucket: 'darwinz-login.appspot.com',
    iosBundleId: 'com.example.loginTask',
  );
}
